name: Variables Template

on: 
  workflow_call: {}  # <-- workflow must be callable

jobs:
  calc:
    runs-on: ubuntu-latest
    outputs:
      COMPANY_NAME: ${{ steps.setvars.outputs.COMPANY_NAME }}
      CURRENT_YEAR: ${{ steps.setvars.outputs.CURRENT_YEAR }}
    steps:
      - id: setvars
        run: |
          echo "COMPANY_NAME=My Company" >> $GITHUB_OUTPUT
          echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_OUTPUT


